baseURL = 'https://Abdouroumi.github.io/'
languageCode = 'en-us'
title = 'E1b1g'
theme = 'poison'
pluralizelisttitles = false

[pagination]
pagerSize = 10

[params]
brand = "E1b1g"
description = "E1b1g's personal blog"
dark_mode = true
front_page_content = ["posts"]

# Menu configuration
menu = [
    {Name = "About", URL = "/about/", HasChildren = false},
    {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
]

# RSS feed
rss_icon = true
rss_section = "posts"

[taxonomies]
series = 'series'
tags = 'tags'
